# Portada de la parte de administraci√≥n
    
backend:
    pattern:   /
    defaults:  { _controller: BackendBundle:Default:login }

backend_index:
    pattern:   /index
    defaults:  { _controller: BackendBundle:Default:index }
    
BackendOficina:
    resource: "@BackendBundle/Resources/config/routing/oficina.yml"
    prefix: /oficina
    
BackendCatedra:
    resource: "@BackendBundle/Resources/config/routing/catedra.yml"
    prefix: /catedra