# Portada de la parte de administraci√≥n
    
backend:
    pattern:   /
    defaults:  { _controller: BackendBundle:Default:index }

backend_index:
    pattern:   /index
    defaults:  { _controller: BackendBundle:Default:index }
    
BackendOficina:
    resource: "@BackendBundle/Resources/config/routing/oficina.yml"
    prefix: /oficina
    
BackendCatedra:
    resource: "@BackendBundle/Resources/config/routing/catedra.yml"
    prefix: /catedra
    
BackendTipodecargo:
    resource: "@BackendBundle/Resources/config/routing/tipodecargo.yml"
    prefix: /tipodecargo
    
BackendPersona:
    resource: "@BackendBundle/Resources/config/routing/persona.yml"
    prefix: /persona
    
BackendConcurso:
    resource: "@BackendBundle/Resources/config/routing/concurso.yml"
    prefix: /concurso